<a href="https://colab.research.google.com/github/Nirtika123/Honda-Subcontinent-Sales-Data-Processing/blob/main/dalab2(15_7).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task 1: Import the required Python library.

In [65]:
import pandas as pd

Task 2: Load the India dataset into a DataFrame.

In [66]:
india=pd.read_csv("hondu_india_sales.csv")
india.head()

,Sale_ID,Month,Model,Segment,Sales_Units,Listed_Price_INR,Customer_Rating_Out_of_5,Discount_INR
0,IN001,Dec_2025,Hondu Activaa 125,Scooter,181604,92400,4.3,3900
1,IN002,Dec_2025,Hondu Diyo 110,Scooter,18609,85700,4.2,3100
2,IN003,Dec_2025,Hondu Shiny 125,Commuter Bike,125266,85600,4.1,2900
3,IN004,Dec_2025,Hondu Unicod 160,Commuter Bike,33640,120200,4.1,6400
4,IN005,Dec_2025,Hondu Highness 350,Premium Bike,2560,224400,4.7,9800

Task 3: Load the Pakistan dataset into a DataFrame.

In [67]:
pakistan=pd.read_csv("hondu_pakistan_sales.csv")
pakistan.head()

,Sale_ID,Month,Model,Segment,Sales_Units,Listed_Price_PKR,Customer_Rating_Out_of_10,Discount_Percentage
0,PK001,Dec_2025,Hondu Activaa 125,Scooter,9901,483800,9.0,6.5
1,PK002,Dec_2025,Hondu Diyo 110,Scooter,943,454200,7.8,8.9
2,PK003,Dec_2025,Hondu Shiny 125,Commuter Bike,6132,452300,8.8,7.3
3,PK004,Dec_2025,Hondu Unicod 160,Commuter Bike,2593,613500,9.0,5.2
4,PK005,Dec_2025,Hondu Highness 350,Premium Bike,148,1208400,8.8,6.5

Task 4: Load the Bangladesh dataset into a DataFrame.

In [68]:
bangladesh=pd.read_csv("hondu_bangladesh_sales.csv")
bangladesh.head()

,Sale_ID,Month,Model,Segment,Sales_Units,Listed_Price_BDT,Customer_Rating_Out_of_5,Discount_BDT
0,BD001,Dec_2025,Hondu Activaa 125,Scooter,10484,152400,4.4,8200
1,BD002,Dec_2025,Hondu Diyo 110,Scooter,1369,151000,4.1,4400
2,BD003,Dec_2025,Hondu Shiny 125,Commuter Bike,5770,145600,4.0,8200
3,BD004,Dec_2025,Hondu Unicod 160,Commuter Bike,1522,202400,4.2,5900
4,BD005,Dec_2025,Hondu Highness 350,Premium Bike,181,392600,4.3,22000

Task 5: Add `Country_Code` to the India dataset.

In [69]:
india["Country_Code"] = "IN"
india.head()

,Sale_ID,Month,Model,Segment,Sales_Units,Listed_Price_INR,Customer_Rating_Out_of_5,Discount_INR,Country_Code
0,IN001,Dec_2025,Hondu Activaa 125,Scooter,181604,92400,4.3,3900,IN
1,IN002,Dec_2025,Hondu Diyo 110,Scooter,18609,85700,4.2,3100,IN
2,IN003,Dec_2025,Hondu Shiny 125,Commuter Bike,125266,85600,4.1,2900,IN
3,IN004,Dec_2025,Hondu Unicod 160,Commuter Bike,33640,120200,4.1,6400,IN
4,IN005,Dec_2025,Hondu Highness 350,Premium Bike,2560,224400,4.7,9800,IN

Task 6: Add `Country_Code` to the Pakistan dataset.

In [70]:
pakistan["Country_Code"] = "PK"
pakistan.head()

,Sale_ID,Month,Model,Segment,Sales_Units,Listed_Price_PKR,Customer_Rating_Out_of_10,Discount_Percentage,Country_Code
0,PK001,Dec_2025,Hondu Activaa 125,Scooter,9901,483800,9.0,6.5,PK
1,PK002,Dec_2025,Hondu Diyo 110,Scooter,943,454200,7.8,8.9,PK
2,PK003,Dec_2025,Hondu Shiny 125,Commuter Bike,6132,452300,8.8,7.3,PK
3,PK004,Dec_2025,Hondu Unicod 160,Commuter Bike,2593,613500,9.0,5.2,PK
4,PK005,Dec_2025,Hondu Highness 350,Premium Bike,148,1208400,8.8,6.5,PK

Task 7: Add `Country_Code` to the Bangladesh dataset.

In [71]:
bangladesh["Country_Code"] = "BD"
bangladesh.head()

,Sale_ID,Month,Model,Segment,Sales_Units,Listed_Price_BDT,Customer_Rating_Out_of_5,Discount_BDT,Country_Code
0,BD001,Dec_2025,Hondu Activaa 125,Scooter,10484,152400,4.4,8200,BD
1,BD002,Dec_2025,Hondu Diyo 110,Scooter,1369,151000,4.1,4400,BD
2,BD003,Dec_2025,Hondu Shiny 125,Commuter Bike,5770,145600,4.0,8200,BD
3,BD004,Dec_2025,Hondu Unicod 160,Commuter Bike,1522,202400,4.2,5900,BD
4,BD005,Dec_2025,Hondu Highness 350,Premium Bike,181,392600,4.3,22000,BD

Task 8: Rename `Customer_Rating_Out_of_5` as `Rating_Out_of_5`.

In [72]:
india.rename(columns={"Customer_Rating_Out_of_5":"Rating_Out_of_5"}, inplace=True)
india.head()

,Sale_ID,Month,Model,Segment,Sales_Units,Listed_Price_INR,Rating_Out_of_5,Discount_INR,Country_Code
0,IN001,Dec_2025,Hondu Activaa 125,Scooter,181604,92400,4.3,3900,IN
1,IN002,Dec_2025,Hondu Diyo 110,Scooter,18609,85700,4.2,3100,IN
2,IN003,Dec_2025,Hondu Shiny 125,Commuter Bike,125266,85600,4.1,2900,IN
3,IN004,Dec_2025,Hondu Unicod 160,Commuter Bike,33640,120200,4.1,6400,IN
4,IN005,Dec_2025,Hondu Highness 350,Premium Bike,2560,224400,4.7,9800,IN

Task 9: Rename `Discount_INR` as `Discount_Amount_INR`.

In [73]:
india.rename(columns={"Discount_INR":"Discount_Amount_INR"}, inplace=True)
india.head()

,Sale_ID,Month,Model,Segment,Sales_Units,Listed_Price_INR,Rating_Out_of_5,Discount_Amount_INR,Country_Code
0,IN001,Dec_2025,Hondu Activaa 125,Scooter,181604,92400,4.3,3900,IN
1,IN002,Dec_2025,Hondu Diyo 110,Scooter,18609,85700,4.2,3100,IN
2,IN003,Dec_2025,Hondu Shiny 125,Commuter Bike,125266,85600,4.1,2900,IN
3,IN004,Dec_2025,Hondu Unicod 160,Commuter Bike,33640,120200,4.1,6400,IN
4,IN005,Dec_2025,Hondu Highness 350,Premium Bike,2560,224400,4.7,9800,IN

Task 10: Create `Final_Price_INR` for the India dataset.

In [74]:
india["Final_Price_INR"] = india["Listed_Price_INR"] - india["Discount_Amount_INR"]
india.head()

,Sale_ID,Month,Model,Segment,Sales_Units,Listed_Price_INR,Rating_Out_of_5,Discount_Amount_INR,Country_Code,Final_Price_INR
0,IN001,Dec_2025,Hondu Activaa 125,Scooter,181604,92400,4.3,3900,IN,88500
1,IN002,Dec_2025,Hondu Diyo 110,Scooter,18609,85700,4.2,3100,IN,82600
2,IN003,Dec_2025,Hondu Shiny 125,Commuter Bike,125266,85600,4.1,2900,IN,82700
3,IN004,Dec_2025,Hondu Unicod 160,Commuter Bike,33640,120200,4.1,6400,IN,113800
4,IN005,Dec_2025,Hondu Highness 350,Premium Bike,2560,224400,4.7,9800,IN,214600

Task 11: Convert Pakistan listed price from PKR to INR and create `Listed_Price_INR`.

In [75]:
pakistan["Listed_Price_INR"] = pakistan["Listed_Price_PKR"] * 0.30
pakistan.head()

,Sale_ID,Month,Model,Segment,Sales_Units,Listed_Price_PKR,Customer_Rating_Out_of_10,Discount_Percentage,Country_Code,Listed_Price_INR
0,PK001,Dec_2025,Hondu Activaa 125,Scooter,9901,483800,9.0,6.5,PK,145140.0
1,PK002,Dec_2025,Hondu Diyo 110,Scooter,943,454200,7.8,8.9,PK,136260.0
2,PK003,Dec_2025,Hondu Shiny 125,Commuter Bike,6132,452300,8.8,7.3,PK,135690.0
3,PK004,Dec_2025,Hondu Unicod 160,Commuter Bike,2593,613500,9.0,5.2,PK,184050.0
4,PK005,Dec_2025,Hondu Highness 350,Premium Bike,148,1208400,8.8,6.5,PK,362520.0

Task 12: Convert Pakistan customer rating from out of 10 to out of 5 and create `Rating_Out_of_5`.

In [76]:
pakistan["Rating_Out_of_5"] = pakistan["Customer_Rating_Out_of_10"] / 2
pakistan.head()

,Sale_ID,Month,Model,Segment,Sales_Units,Listed_Price_PKR,Customer_Rating_Out_of_10,Discount_Percentage,Country_Code,Listed_Price_INR,Rating_Out_of_5
0,PK001,Dec_2025,Hondu Activaa 125,Scooter,9901,483800,9.0,6.5,PK,145140.0,4.5
1,PK002,Dec_2025,Hondu Diyo 110,Scooter,943,454200,7.8,8.9,PK,136260.0,3.9
2,PK003,Dec_2025,Hondu Shiny 125,Commuter Bike,6132,452300,8.8,7.3,PK,135690.0,4.4
3,PK004,Dec_2025,Hondu Unicod 160,Commuter Bike,2593,613500,9.0,5.2,PK,184050.0,4.5
4,PK005,Dec_2025,Hondu Highness 350,Premium Bike,148,1208400,8.8,6.5,PK,362520.0,4.4

Task 13: Convert Pakistan percentage discount into discount amount in INR and create `Discount_Amount_INR`.

In [77]:
pakistan["Discount_Amount_INR"] = (pakistan["Listed_Price_INR"] *pakistan["Discount_Percentage"] / 100)
pakistan.head()

,Sale_ID,Month,Model,Segment,Sales_Units,Listed_Price_PKR,Customer_Rating_Out_of_10,Discount_Percentage,Country_Code,Listed_Price_INR,Rating_Out_of_5,Discount_Amount_INR
0,PK001,Dec_2025,Hondu Activaa 125,Scooter,9901,483800,9.0,6.5,PK,145140.0,4.5,9434.10
1,PK002,Dec_2025,Hondu Diyo 110,Scooter,943,454200,7.8,8.9,PK,136260.0,3.9,12127.14
2,PK003,Dec_2025,Hondu Shiny 125,Commuter Bike,6132,452300,8.8,7.3,PK,135690.0,4.4,9905.37
3,PK004,Dec_2025,Hondu Unicod 160,Commuter Bike,2593,613500,9.0,5.2,PK,184050.0,4.5,9570.60
4,PK005,Dec_2025,Hondu Highness 350,Premium Bike,148,1208400,8.8,6.5,PK,362520.0,4.4,23563.80

Task 14: Create `Final_Price_INR` for the Pakistan dataset.

In [78]:
pakistan["Final_Price_INR"] = (
    pakistan["Listed_Price_INR"]
    - pakistan["Discount_Amount_INR"])
pakistan.head()

,Sale_ID,Month,Model,Segment,Sales_Units,Listed_Price_PKR,Customer_Rating_Out_of_10,Discount_Percentage,Country_Code,Listed_Price_INR,Rating_Out_of_5,Discount_Amount_INR,Final_Price_INR
0,PK001,Dec_2025,Hondu Activaa 125,Scooter,9901,483800,9.0,6.5,PK,145140.0,4.5,9434.10,135705.90
1,PK002,Dec_2025,Hondu Diyo 110,Scooter,943,454200,7.8,8.9,PK,136260.0,3.9,12127.14,124132.86
2,PK003,Dec_2025,Hondu Shiny 125,Commuter Bike,6132,452300,8.8,7.3,PK,135690.0,4.4,9905.37,125784.63
3,PK004,Dec_2025,Hondu Unicod 160,Commuter Bike,2593,613500,9.0,5.2,PK,184050.0,4.5,9570.60,174479.40
4,PK005,Dec_2025,Hondu Highness 350,Premium Bike,148,1208400,8.8,6.5,PK,362520.0,4.4,23563.80,338956.20

Task 15: Convert Bangladesh listed price from BDT to INR and create `Listed_Price_INR`.

In [79]:
bangladesh["Listed_Price_INR"] = bangladesh["Listed_Price_BDT"] * 0.70
bangladesh.head()

,Sale_ID,Month,Model,Segment,Sales_Units,Listed_Price_BDT,Customer_Rating_Out_of_5,Discount_BDT,Country_Code,Listed_Price_INR
0,BD001,Dec_2025,Hondu Activaa 125,Scooter,10484,152400,4.4,8200,BD,106680.0
1,BD002,Dec_2025,Hondu Diyo 110,Scooter,1369,151000,4.1,4400,BD,105700.0
2,BD003,Dec_2025,Hondu Shiny 125,Commuter Bike,5770,145600,4.0,8200,BD,101920.0
3,BD004,Dec_2025,Hondu Unicod 160,Commuter Bike,1522,202400,4.2,5900,BD,141680.0
4,BD005,Dec_2025,Hondu Highness 350,Premium Bike,181,392600,4.3,22000,BD,274820.0

Task 16:Rename `Customer_Rating_Out_of_5` as `Rating_Out_of_5`.

In [80]:
bangladesh.rename(columns={"Customer_Rating_Out_of_5":"Rating_Out_of_5"}, inplace=True)
bangladesh.head()

,Sale_ID,Month,Model,Segment,Sales_Units,Listed_Price_BDT,Rating_Out_of_5,Discount_BDT,Country_Code,Listed_Price_INR
0,BD001,Dec_2025,Hondu Activaa 125,Scooter,10484,152400,4.4,8200,BD,106680.0
1,BD002,Dec_2025,Hondu Diyo 110,Scooter,1369,151000,4.1,4400,BD,105700.0
2,BD003,Dec_2025,Hondu Shiny 125,Commuter Bike,5770,145600,4.0,8200,BD,101920.0
3,BD004,Dec_2025,Hondu Unicod 160,Commuter Bike,1522,202400,4.2,5900,BD,141680.0
4,BD005,Dec_2025,Hondu Highness 350,Premium Bike,181,392600,4.3,22000,BD,274820.0

Task 17: Convert Bangladesh discount from BDT to INR and create `Discount_Amount_INR`.

In [81]:
bangladesh["Discount_Amount_INR"] = bangladesh["Discount_BDT"] * 0.70
bangladesh.head()

,Sale_ID,Month,Model,Segment,Sales_Units,Listed_Price_BDT,Rating_Out_of_5,Discount_BDT,Country_Code,Listed_Price_INR,Discount_Amount_INR
0,BD001,Dec_2025,Hondu Activaa 125,Scooter,10484,152400,4.4,8200,BD,106680.0,5740.0
1,BD002,Dec_2025,Hondu Diyo 110,Scooter,1369,151000,4.1,4400,BD,105700.0,3080.0
2,BD003,Dec_2025,Hondu Shiny 125,Commuter Bike,5770,145600,4.0,8200,BD,101920.0,5740.0
3,BD004,Dec_2025,Hondu Unicod 160,Commuter Bike,1522,202400,4.2,5900,BD,141680.0,4130.0
4,BD005,Dec_2025,Hondu Highness 350,Premium Bike,181,392600,4.3,22000,BD,274820.0,15400.0

Task 18: Create `Final_Price_INR` for the Bangladesh dataset.

In [82]:
bangladesh["Final_Price_INR"] = bangladesh["Listed_Price_BDT"] - bangladesh["Discount_BDT"]
bangladesh.head()

,Sale_ID,Month,Model,Segment,Sales_Units,Listed_Price_BDT,Rating_Out_of_5,Discount_BDT,Country_Code,Listed_Price_INR,Discount_Amount_INR,Final_Price_INR
0,BD001,Dec_2025,Hondu Activaa 125,Scooter,10484,152400,4.4,8200,BD,106680.0,5740.0,144200
1,BD002,Dec_2025,Hondu Diyo 110,Scooter,1369,151000,4.1,4400,BD,105700.0,3080.0,146600
2,BD003,Dec_2025,Hondu Shiny 125,Commuter Bike,5770,145600,4.0,8200,BD,101920.0,5740.0,137400
3,BD004,Dec_2025,Hondu Unicod 160,Commuter Bike,1522,202400,4.2,5900,BD,141680.0,4130.0,196500
4,BD005,Dec_2025,Hondu Highness 350,Premium Bike,181,392600,4.3,22000,BD,274820.0,15400.0,370600

Task 19: Keep only the required final columns in the India dataset

In [83]:
final_columns = [
    "Sale_ID",
    "Month",
    "Country_Code",
    "Model",
    "Segment",
    "Sales_Units",
    "Listed_Price_INR",
    "Rating_Out_of_5",
    "Discount_Amount_INR",
    "Final_Price_INR"
]
india = india[final_columns]
india.head()

,Sale_ID,Month,Country_Code,Model,Segment,Sales_Units,Listed_Price_INR,Rating_Out_of_5,Discount_Amount_INR,Final_Price_INR
0,IN001,Dec_2025,IN,Hondu Activaa 125,Scooter,181604,92400,4.3,3900,88500
1,IN002,Dec_2025,IN,Hondu Diyo 110,Scooter,18609,85700,4.2,3100,82600
2,IN003,Dec_2025,IN,Hondu Shiny 125,Commuter Bike,125266,85600,4.1,2900,82700
3,IN004,Dec_2025,IN,Hondu Unicod 160,Commuter Bike,33640,120200,4.1,6400,113800
4,IN005,Dec_2025,IN,Hondu Highness 350,Premium Bike,2560,224400,4.7,9800,214600

Task 20: Keep only the required final columns in the Pakistan dataset.

In [84]:
pakistan = pakistan[final_columns]
pakistan.head()

,Sale_ID,Month,Country_Code,Model,Segment,Sales_Units,Listed_Price_INR,Rating_Out_of_5,Discount_Amount_INR,Final_Price_INR
0,PK001,Dec_2025,PK,Hondu Activaa 125,Scooter,9901,145140.0,4.5,9434.10,135705.90
1,PK002,Dec_2025,PK,Hondu Diyo 110,Scooter,943,136260.0,3.9,12127.14,124132.86
2,PK003,Dec_2025,PK,Hondu Shiny 125,Commuter Bike,6132,135690.0,4.4,9905.37,125784.63
3,PK004,Dec_2025,PK,Hondu Unicod 160,Commuter Bike,2593,184050.0,4.5,9570.60,174479.40
4,PK005,Dec_2025,PK,Hondu Highness 350,Premium Bike,148,362520.0,4.4,23563.80,338956.20

Task 21: Keep only the required final columns in the Bangladesh dataset.

In [85]:
bangladesh = bangladesh[final_columns]
bangladesh.head()

,Sale_ID,Month,Country_Code,Model,Segment,Sales_Units,Listed_Price_INR,Rating_Out_of_5,Discount_Amount_INR,Final_Price_INR
0,BD001,Dec_2025,BD,Hondu Activaa 125,Scooter,10484,106680.0,4.4,5740.0,144200
1,BD002,Dec_2025,BD,Hondu Diyo 110,Scooter,1369,105700.0,4.1,3080.0,146600
2,BD003,Dec_2025,BD,Hondu Shiny 125,Commuter Bike,5770,101920.0,4.0,5740.0,137400
3,BD004,Dec_2025,BD,Hondu Unicod 160,Commuter Bike,1522,141680.0,4.2,4130.0,196500
4,BD005,Dec_2025,BD,Hondu Highness 350,Premium Bike,181,274820.0,4.3,15400.0,370600

Task 22: Combine the three standardized national datasets into one regional dataset.

In [86]:
regional = pd.concat(
    [india, pakistan, bangladesh],
    ignore_index=True)

regional.head()

,Sale_ID,Month,Country_Code,Model,Segment,Sales_Units,Listed_Price_INR,Rating_Out_of_5,Discount_Amount_INR,Final_Price_INR
0,IN001,Dec_2025,IN,Hondu Activaa 125,Scooter,181604,92400.0,4.3,3900.0,88500.0
1,IN002,Dec_2025,IN,Hondu Diyo 110,Scooter,18609,85700.0,4.2,3100.0,82600.0
2,IN003,Dec_2025,IN,Hondu Shiny 125,Commuter Bike,125266,85600.0,4.1,2900.0,82700.0
3,IN004,Dec_2025,IN,Hondu Unicod 160,Commuter Bike,33640,120200.0,4.1,6400.0,113800.0
4,IN005,Dec_2025,IN,Hondu Highness 350,Premium Bike,2560,224400.0,4.7,9800.0,214600.0

Task 23: Reset the index of the final regional dataset.

In [87]:
regional = regional.reset_index(drop=True)
regional.head()

,Sale_ID,Month,Country_Code,Model,Segment,Sales_Units,Listed_Price_INR,Rating_Out_of_5,Discount_Amount_INR,Final_Price_INR
0,IN001,Dec_2025,IN,Hondu Activaa 125,Scooter,181604,92400.0,4.3,3900.0,88500.0
1,IN002,Dec_2025,IN,Hondu Diyo 110,Scooter,18609,85700.0,4.2,3100.0,82600.0
2,IN003,Dec_2025,IN,Hondu Shiny 125,Commuter Bike,125266,85600.0,4.1,2900.0,82700.0
3,IN004,Dec_2025,IN,Hondu Unicod 160,Commuter Bike,33640,120200.0,4.1,6400.0,113800.0
4,IN005,Dec_2025,IN,Hondu Highness 350,Premium Bike,2560,224400.0,4.7,9800.0,214600.0

Task 24: Display the shape of the final regional dataset.

In [88]:
regional.shape

(90, 10)

Task 25: Check the data types of the final regional dataset.

In [89]:
regional.dtypes

Sale_ID                 object
Month                   object
Country_Code            object
Model                   object
Segment                 object
Sales_Units              int64
Listed_Price_INR       float64
Rating_Out_of_5        float64
Discount_Amount_INR    float64
Final_Price_INR        float64
dtype: object

Task 26: Check missing values in the final regional dataset.

In [90]:
regional.isnull().sum()

Sale_ID                0
Month                  0
Country_Code           0
Model                  0
Segment                0
Sales_Units            0
Listed_Price_INR       0
Rating_Out_of_5        0
Discount_Amount_INR    0
Final_Price_INR        0
dtype: int64

Task 27: Check duplicate records in the final regional dataset.

In [91]:
regional.duplicated().sum()

np.int64(0)

Task 28: Display the final top five records of the processed regional dataset.

In [92]:
regional.head()

,Sale_ID,Month,Country_Code,Model,Segment,Sales_Units,Listed_Price_INR,Rating_Out_of_5,Discount_Amount_INR,Final_Price_INR
0,IN001,Dec_2025,IN,Hondu Activaa 125,Scooter,181604,92400.0,4.3,3900.0,88500.0
1,IN002,Dec_2025,IN,Hondu Diyo 110,Scooter,18609,85700.0,4.2,3100.0,82600.0
2,IN003,Dec_2025,IN,Hondu Shiny 125,Commuter Bike,125266,85600.0,4.1,2900.0,82700.0
3,IN004,Dec_2025,IN,Hondu Unicod 160,Commuter Bike,33640,120200.0,4.1,6400.0,113800.0
4,IN005,Dec_2025,IN,Hondu Highness 350,Premium Bike,2560,224400.0,4.7,9800.0,214600.0

Task 29: Save the final regional dataset as `hondu_subcontinent_processed.csv`.

In [64]:
regional.to_csv("hondu_subcontinent_processed.csv", index=False)
print("File saved successfully!")

File saved successfully!